apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: uptimizerapps.uptimizer.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: uptimizer.com
  # list of versions supported by this CRD
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  description: "Docker image for the Uptimizer application."
                replicas:
                  type: integer
                  minimum: 0
                  description: "Number of application pods."
                  default: 1
                port:
                  type: integer
                  description: "Port the application listens on inside the container."
                  default: 5000
                serviceType:
                  type: string
                  enum: [ClusterIP, NodePort, LoadBalancer]
                  description: "Type of Kubernetes Service to expose the application."
                  default: ClusterIP
                configJson:
                  type: string # Store as potentially large string
                  description: "JSON configuration content for config.json as a string."
                  # x-kubernetes-preserve-unknown-fields: true # Use if JSON structure is highly variable and validation isn't critical
              required:
                - image # Make image mandatory
                - configJson # Make config mandatory
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true # Allows operator to add arbitrary status fields
              properties:
                observedGeneration:
                   type: integer
                   description: "The generation observed by the operator."
                deploymentName:
                   type: string
                serviceName:
                   type: string
                configMapName:
                   type: string
                error:
                   type: string
                   description: "Last encountered error during reconciliation."
                # Add more status fields as needed (e.g., readyReplicas, serviceUrl)
          required: # Top-level required fields
            - spec
  scope: Namespaced # CRs will exist within specific namespaces
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: uptimizerapps
    # singular name to be used as an alias on the CLI and for display
    singular: uptimizerapp
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: UptimizerApp
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - uapp